name: Docker Image CI

on:
  push:
    tags:
      - 'nginx-builder*'

jobs:
  build-deploy-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t wwzpeople/nginx-builder .
        working-directory: base-image/nginx-builder
      - name: push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wwzpeople/nginx-builder
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: base-image/nginx-builder
