name: Docker Image CI

on:
  push:
    tags:
      - 'gradle6-base*'

jobs:
  build-gradle6-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t wwzpeople/gradle6-base .
        working-directory: base-image/gradle6-base
      - name: push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wwzpeople/gradle6-base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: base-image/gradle6-base
