name: Docker Image CI

on:
  push:
    tags:
      - 'yum-repo*'

jobs:
  build-yum-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t wwzpeople/centos7 .
        working-directory: base-image/yum-repo
      - name: push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wwzpeople/centos7
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: base-image/yum-repo
