name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-boot-base:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'boot-base')"
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t wwzpeople/boot-base .
        working-directory: base-image/boot-base
      - name: push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wwzpeople/boot-base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: base-image/boot-base
