name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-jdk11:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'openjdk11')"
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t wwzpeople/openjdk11 .
        working-directory: base-image/openjdk11
      - name: push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wwzpeople/openjdk11
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: base-image/openjdk11